export { default as Dashboard } from './Dashboard'
export { default as Login } from './Login'
export { default as Wallet } from './Wallet'
export { default as Settings} from './Settings'
export { default as Analitycs } from './Analitycs'